export const INIT_LOAD_STOCK = 'ACTION_INIT_LOAD_STOCK';
export const SELECT_STOCK = 'ACTION_SELECT_STOCK';
export const REMOVE_STOCK = 'ACTION_REMOVE_STOCK';
export const ADD_STOCK = 'ACTION_ADD_STOCK';
export const REFRESH_STOCK_INFO = 'ACTION_REFRESH_STOCK_INFO';
export const REFRESH_STOCK_HISTORY = 'ACTION_REFRESH_STOCK_HISTORY';